export enum ELECTION_STATUS {
    DRAFT = "DRAFT",
    ENABLED = "ENABLED",
    NOMINATIONS = "NOMINATIONS",
    RUNNING = "RUNNING",
    COMPLETE = "COMPLETE",
    CANCELLED = "CANCELLED",
}
export enum ELECTION_MODE {
    SCHEDULE = "SCHEDULE",
    MANUAL = "MANUAL",
}
export enum RESPONSE_TYPE {
    YES_NO = "YES_NO",
    RANKING = "RANKING",
    PREFERENCE = "PREFERENCE",
    FIRST_PAST = "FIRST_PAST"
}